### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [sw355498/git-workshop#1]
> 學習的過程中不要一味的為了追求短期的成效，要實際去了解所學習的內容才能夠真正的將知識所吸收。

謝謝你完成作業，也完全抓到了我請你們看這部影片的重點之一，讓我們耐下心來，在接下來幾天課程中，好好地理解跟吸收我們上課討論的內容。

**Comment by sw355498** [comment]
感列老師的回覆，會再努力理解及跟上討論的內容
